name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  test_project:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20.5.1"
      - uses: pnpm/action-setup@v2
        with:
          version: "8.6.12"
      - name: Install backend deps
        run: pnpm install
      - name: Install frontend deps
        run: |
          cd frontend
          pnpm install
      - name: Lint project
        run: pnpm lint
      - name: Build frontend
        run: |
          cd frontend
          pnpm build
      - name: Run vitest tests
        run: |
          cd frontend
          pnpm test
      - name: Run cypress e2e tests
        uses: cypress-io/github-action@v5
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        with:
          command: pnpm test:e2e
          start: pnpm start
          browser: chrome

  tag_release:
    needs: test_project
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@c360518fb8131e99795f8208f8a6105ceca55ec2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch

  deploy_project:
    needs: tag_release
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Fly deploy
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  notify_on_success:
    needs: deploy_project
    runs-on: ubuntu-20.04
    if: success()
    steps:
      - name: Notify Discord if deploy successful
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          text: Phonebook deploy succeeded
          description: All is well with https://full-stack-open-phonebook-cicd.fly.dev
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK}}

  nofity_on_fail:
    needs: [test_project, tag_release, deploy_project]
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' && failure()}}
    steps:
      - name: Notify Discord if deploy fails
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          text: Phonebook deploy failed
          description: User ${{ github.event.head_commit.author.username }} broke the build with ${{ github.event.head_commit.url }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK}}
